### ISSUE TITLE
[BUG] Pipeline build failing for fedora-32

### ISSUE THREAD

**Issue by avisiedo** [freeipa/freeipa-openshift-container#13]
### Description

Failing container image build for fedora-32 when applying the list of patches.

### Frequency

[x] Always

### Wrong behaviour

The container build fail on the step which apply the patches.

### Expected behaviour

The container build properly all the stages.

### Additional information

https://travis-ci.org/github/freeipa/freeipa-openshift-container/builds/722950449

**Comment by frasertweedale** [comment]
Fixed in https://github.com/freeipa/freeipa-openshift-container/pull/16.
